eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
#spring:
#   application:
#      name: service-one
#   datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/practice
#    username: root
#    password: root
#   jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        ddl-auto: update
#    show-sql: true
      
user:
  name:rameshe
  
  


