eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
spring:
   application:
      name: service-one
    profiles:
      active:
        - dev
      
user:
  name: Ejjagiri Ramesh
  password: Ramesh@234PROD
  
  


